services:
  db_inventario:
    container_name: db_inventario
    image: mysql:8.0.37
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
  app_backend_dev:
    container_name: backend_dev
    build: .
    image: backend_inventario:1
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db_inventario
  app_backend_prod:
    container_name: backend_prod
    build: .
    image: backend_inventario:1
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db_inventario
volumes:
  mysql-data: