services:
  db_inventario:
    container_name: db_inventario
    image: mysql:8.0.37
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_inventario_dev
      MYSQL_ROOT_PASSWORD: 123
