server:
  port: 8080
spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: resfullApiInventario
  datasource:
    password: 123
    url: jdbc:mysql://db_inventario:3306/db_inventario_dev
    username: root
  jpa:
    database: MySQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: mysql
  jackson:
    time-zone: America/Mexico_City

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: resfullApiInventario
  datasource:
    password: 123
    url: jdbc:mysql://db_inventario:3306/db_inventario_prod
    username: root
  jpa:
    database: MySQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: mysql
  jackson:
    time-zone: America/Mexico_City